version: "2"

run:
  timeout: 2m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - revive
    - gosimple
    - unused
    - structcheck

linters-settings:
  goanalysis:
    build-tags:
      - gui
