# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - golangci-lint fmt
      - go test -race -p=1 ./...
      - go test -race -v -bench=. -benchmem ./...
      - task lint
  
  fmt:
    cmds:
      - golangci-lint fmt
      - goimports -local github.com/dyammarcano/presencial -w .
  
  lint:
    cmds:
      - golangci-lint run --no-config --enable=errcheck,govet,ineffassign,staticcheck,unused,revive,gosec,goconst,gocyclo,misspell,unconvert,unparam,gocritic,nakedret ./...
