name: Build and Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
        check-latest: true
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev
        sudo apt-get install -y libasound2-dev libpulse-dev
    
    - name: Build
      run: go build -v -o build/linux/app ./...

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-linux
        path: build/linux/app

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
        check-latest: true
    
    - name: Build
      run: go build -v -o build/windows/app.exe ./...

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-windows
        path: build/windows/app.exe
